package com.universidad.modelo.negocio;
// Generated 5/08/2021 06:13:15 PM by Hibernate Tools 4.0.1.Final

/**
 * CatDepto generated by hbm2java
 */
public class CatDepto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8782111947472016847L;
	private int idDepto;
	private String nombre;
	
	private CatEmpresa catEmpresa;

	public CatDepto() {
	}


	public int getIdDepto() {
		return this.idDepto;
	}

	public void setIdDepto(int idDepto) {
		this.idDepto = idDepto;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + idDepto;
		return result;
	}


	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CatDepto other = (CatDepto) obj;
		if (idDepto != other.idDepto)
			return false;
		return true;
	}


	public CatEmpresa getCatEmpresa() {
		return catEmpresa;
	}


	public void setCatEmpresa(CatEmpresa catEmpresa) {
		this.catEmpresa = catEmpresa;
	}


}
