package com.universidad.modelo.negocio;
// Generated 5/08/2021 06:13:15 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * CatEmpresa generated by hbm2java
 */
public class CatEmpresa implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2427195277497314602L;
	private int idEmpresa;
	private String descripcion;
	private Boolean estatus;

	public CatEmpresa() {
	}

	

	public int getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(int idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Boolean getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Boolean estatus) {
		this.estatus = estatus;
	}



	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + idEmpresa;
		return result;
	}



	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CatEmpresa other = (CatEmpresa) obj;
		if (idEmpresa != other.idEmpresa)
			return false;
		return true;
	}

	

}
