package com.universidad.modelo.negocio;
// Generated 5/08/2021 06:13:15 PM by Hibernate Tools 4.0.1.Final

/**
 * CatGrupo generated by hbm2java
 */
public class CatGrupo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7147673819967416020L;
	private int id;
	private String descripcion;
	private Boolean estatus;

	public CatGrupo() {
	}

	

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Boolean getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Boolean estatus) {
		this.estatus = estatus;
	}



	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}



	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CatGrupo other = (CatGrupo) obj;
		if (id != other.id)
			return false;
		return true;
	}

}
