package com.universidad.modelo.negocio;
// Generated 5/08/2021 06:13:15 PM by Hibernate Tools 4.0.1.Final

/**
 * EmpleGrupoId generated by hbm2java
 */
public class EmpleGrupoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1137129735695283017L;
	private int idEmpleado;
	private int idGrupo;

	public EmpleGrupoId() {
	}

	

	public int getIdEmpleado() {
		return this.idEmpleado;
	}

	public void setIdEmpleado(int idEmpleado) {
		this.idEmpleado = idEmpleado;
	}

	public int getIdGrupo() {
		return this.idGrupo;
	}

	public void setIdGrupo(int idGrupo) {
		this.idGrupo = idGrupo;
	}



	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + idEmpleado;
		result = prime * result + idGrupo;
		return result;
	}



	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		EmpleGrupoId other = (EmpleGrupoId) obj;
		if (idEmpleado != other.idEmpleado)
			return false;
		if (idGrupo != other.idGrupo)
			return false;
		return true;
	}



}
