package com.universidad.modelo.negocio;
// Generated 5/08/2021 06:13:15 PM by Hibernate Tools 4.0.1.Final

/**
 * EmpleGrupo generated by hbm2java
 */
public class EmpleGrupo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7391714660774768641L;
	private EmpleGrupoId id;
	private String comentario;

	public EmpleGrupo() {
	}

	

	public EmpleGrupoId getId() {
		return this.id;
	}

	public void setId(EmpleGrupoId id) {
		this.id = id;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}



	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}



	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		EmpleGrupo other = (EmpleGrupo) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}
