package com.universidad.modelo.negocio;
// Generated 5/08/2021 06:13:15 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * Empleado generated by hbm2java
 */
public class Empleado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1247975695579743393L;
	private int id;
	private CatDepto catDepto;
	private CatEmpresa catEmpresa;
	private String nombre;
	private String ape1;
	private String ape2;
	private Date fecNacimiento;
	private String correo;
	private Integer genero;
	private String telefono;
	private String celular;
	private Date fecIngreso;

	public Empleado() {
	}

	
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public CatDepto getCatDepto() {
		return this.catDepto;
	}

	public void setCatDepto(CatDepto catDepto) {
		this.catDepto = catDepto;
	}

	public CatEmpresa getCatEmpresa() {
		return this.catEmpresa;
	}

	public void setCatEmpresa(CatEmpresa catEmpresa) {
		this.catEmpresa = catEmpresa;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApe1() {
		return this.ape1;
	}

	public void setApe1(String ape1) {
		this.ape1 = ape1;
	}

	public String getApe2() {
		return this.ape2;
	}

	public void setApe2(String ape2) {
		this.ape2 = ape2;
	}

	public Date getFecNacimiento() {
		return this.fecNacimiento;
	}

	public void setFecNacimiento(Date fecNacimiento) {
		this.fecNacimiento = fecNacimiento;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public Integer getGenero() {
		return this.genero;
	}

	public void setGenero(Integer genero) {
		this.genero = genero;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public Date getFecIngreso() {
		return this.fecIngreso;
	}

	public void setFecIngreso(Date fecIngreso) {
		this.fecIngreso = fecIngreso;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}


	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Empleado other = (Empleado) obj;
		if (id != other.id)
			return false;
		return true;
	}

}
